# Generated by Django 3.0.5 on 2020-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=500)),
                ('section', models.IntegerField()),
                ('department', models.CharField(max_length=500)),
                ('instructorname', models.CharField(max_length=500)),
            ],
        ),
    ]
